# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6a65bff4d7fd69f037f0734956f2ab168bd7b2e09c49665005d08335b5b77c3ac3467964c2cfca77a211e6ac23ff24db31aa6c56930b6905d9be39e1ec7cb8d

test:
  secret_key_base: 04e0305f6d5ede1a990a187aef767a896effa0800fd37758a11eaccd65c9efa8a6b59d040ac0f50a1da5b85ee8b6c28242ae42ed2e9cda0f58759ba00f25847a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
